sudo: false

env:
  global:
    - secure: "plfyK5+gp1nOuI7t/RpAsOwGU1LgEDgNk1MvNbRkN1fzbfWppTfQHoArGyuVRuKe7t9IOE12+t6R0F2AQoRdpV6v7xeQL003UqM9CvQhxU3s6y4dH1T8BLXtI/6r9BqRhEHAWb7iUKJxei7M1DPwun+VnGSmnrD0X5nOqXeCglODDncmkOuN5IMFNPMP71gsjIGxpqZhh7IRuF4/tRo8xhuHm1WlHvZH20CdRLsf6u1KBk1svI4U4O7PEbqkWytt1avFUiUIjtl7ISd/C68Bnm1EgfHCyiNjNatbWp5v+utGLliU88bl/iyldYUJvOc8XhYqTR+ETYzfuMhIJnkVR6dgLpijVapyLfupJQO559oXtNK9oqDj0QziJD0t1c70dz/BJme6nze6UG6YmhglXS/zpp6afsoa1HCjfXsJPxbWqmrbNPUhBIj2EQXDMYN+F24RC1W7H494DtfN4ZCxt1X+e4RoXw87MGh1XPkCc5di7MBqYsK88oawWTMGd6oHWhdExuGdSDDj9unTT+PnwtmZxzyo88yzBxvh32i9yAEDDh1by5+Qw7zXWZHcOHCBEq54U6Xr6fiz6QrNwI2H8BwzS/DUwdgszXyjKZHUNkXVED253dU4LN4xZYxjZAke91pQKbtj+ambt0yepVSPthWUb2jVkw4JTjNoSYWPS08="
    - secure: "s+r08mr4CABrGs5wOwWKrYclUfnyA1F2FMFcTz72bPvWP1HP48AzggEI6pnMz8NCMcQdXTU4hf7c2KqMUi0lSWlP7suscaq1YMlP2VCPBv8iDZPCNKEtOKeuOj24voxhlffIHqwq5JT5tLDRKOWGwUbQFWeOtZPZ01+uC0i25RK04uH1nDzNeEd+ceeYarqnOlDU9Yo34s/Jg18KBVaKXk1e80C78HBnzzvCvgxbseTW0+g5UJ3JfzQ/x8JaCM9Nzlso1aglgHYDSqBW3QbRCwceu2qD3O2T/0kqY7jHzBQTEhOZ5EK189izuYS7ZGIm4nnKXvnhgtLCJbBDEebD5mKfURzqKqQMKNFD15g4hz7SPimpeQhabXCEiSih9zkRt2Lus4J9fFfIP4ZGhB/ien812nmovkvz799y5Ore5ezlN0rwcYc4wqVoxyGHl7ikK/NPRTfkErHRfG4549220NzzdaGBCoi/S/0+POsY5izuaX+HKdy9X1U/em31LdVLgzw0BNbHA6NNEb/3oYMD5WY/GRRLvpvNqRB6cNpZ50CckPp3kelgzL3uzIYgRH4MWsjAtzlBGp1i5H6p5U1sL9uzjTrCoU3EjW5RYYTeks7gxT8RMJPK1o1ClU1s7uEmbmU7u9tCRmIHEQ894bOWXSLM2kh3uuMun8ehwyLwkag="
    - secure: "qi4lAkhdNAeoES8iHjdJCDA76op2uLk6sIgCLIzJY5tN/64K5FisOb/IS0fA7rRToIoTXfwSsnwc2cVDzSKkKXFmTG3KNGExYWbbBvrhEOBSaX+QcHLowiDGnz3Y94N77HH4ACVtCOWq7jWByur3Pv3mCl6YxriE7FrUI/lZJ5ykD3Lx6QhfkUZSfI8ZtYyhZeOdBnlTYryDfMPuD3SqCKVMkdEe/dl2jnFtwS/C61Gp+kEKNoqOEcsnjwdexwngrLFlkOEaekd2TGqMOF8avQ0zAFJouOhAYokbHQT6jb7wYODrXVqsY+oIIP23z6TTmGEh7g2lWspR7r60gfdOJ8B1iDUSzyI6YUU1J5hu3NhCrEAHiJA/QmubYybeC18zkqK/ZHsgoZOY2KdAE37LNDncMUv2BuBEoMil52gj/e+GQzsI7efj6zb/aTnNGlpaiIGNwn9mKg57lSxaBLObBF9MSkfEhiQqwx8L5JgAvhaIUPjRObyMPgccIkybpgCQzBGa1yoGjWaBQqpSqXrMjcobwe57oIaq6o8Lyp8L6T6mQtqn3TEimkqwe54QvQ9YV3ShUOnRrO1MRH5w/C1+Q8On5rwu6njnHrZBrLuO+MZwSN0Pr5UZRPj/sq6I6TO36p4PXDJaWvOSOsl5D9awKhaVrC6F4eIdRjrvzIhWuMU="

before_install:
  - openssl aes-256-cbc -K $encrypted_44a5940e6471_key -iv $encrypted_44a5940e6471_iv
    -in .travis/deploy-key.enc -out .travis/deploy-key -d
  - chmod 600 .travis/deploy-key

  # Install Docker Machine.
  - curl -sL https://github.com/docker/machine/releases/download/v0.8.2/docker-machine-`uname -s`-`uname -m` > docker-machine
  - chmod +x docker-machine

  # Install Docker Compose.
  - curl -sL https://github.com/docker/compose/releases/download/1.4.0/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose

  # Create an .env file from the example.
  - cp .env.example .env

before_script:
  - ./docker-machine create -d generic
    --generic-ip-address direct.broadcast.radiomodem.dk
    --generic-ssh-user root
    --generic-ssh-key ./.travis/deploy-key
    broadcast.radiomodem.dk
  - eval `./docker-machine env broadcast.radiomodem.dk`

script:
  - ./docker-compose build
  - ./docker-compose up -d
